# Optional Pages deployment; the default wrangler.toml targets Workers.
name = "ensemble"
compatibility_date = "2025-09-13"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "ensemble"
database_id = "d2137c96-5f9a-4749-b5e0-c16fd5734de1"
migrations_dir = "migrations"
